# Generated by Django 4.2.8 on 2024-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_rename_item_order_items_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.IntegerField(default=100000),
        ),
    ]
