# Generated by Django 4.2.8 on 2024-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
